services:
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/PrakashMN/HealthBot
    region: singapore
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        value: 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
  - type: web
    name: frontend
    runtime: static
    repo: https://github.com/PrakashMN/HealthBot
    rootDir: frontend-v2
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html